[pytest]
addopts = -ra --strict-markers --maxfail=1
testpaths = ../../packages/bijux-vex/tests
markers =
    e2e: end-to-end tests
    slow: slow tests
pythonpath =
    ../../packages/bijux-vex/src
    ../../packages/bijux-vex
filterwarnings =
    ignore:'HTTP_422_UNPROCESSABLE_ENTITY' is deprecated:DeprecationWarning:anyio._backends._asyncio
    ignore:Not saving anything, no benchmarks have been run!:pytest_benchmark.logger.PytestBenchmarkWarning
