# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi

ROOT_PACKAGE_TARGETS := test lint quality security api build sbom clean

ROOT_TARGET_PACKAGES_test := $(PRIMARY_PACKAGES)
ROOT_TARGET_PACKAGES_lint := $(CHECK_PACKAGES)
ROOT_TARGET_PACKAGES_quality := $(CHECK_PACKAGES)
ROOT_TARGET_PACKAGES_security := $(CHECK_PACKAGES)
ROOT_TARGET_PACKAGES_api := $(PRIMARY_PACKAGES)
ROOT_TARGET_PACKAGES_build := $(PRIMARY_PACKAGES)
ROOT_TARGET_PACKAGES_sbom := $(PRIMARY_PACKAGES)
ROOT_TARGET_PACKAGES_clean := $(ALL_PACKAGES)

ROOT_TARGET_SHARED_ENV_test := 0
ROOT_TARGET_SHARED_ENV_lint := 1
ROOT_TARGET_SHARED_ENV_quality := 1
ROOT_TARGET_SHARED_ENV_security := 1
ROOT_TARGET_SHARED_ENV_api := 0
ROOT_TARGET_SHARED_ENV_build := 0
ROOT_TARGET_SHARED_ENV_sbom := 0
ROOT_TARGET_SHARED_ENV_clean := 0

ROOT_TARGET_POST_clean = @$(MAKE) clean-root-artifacts
