# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi

"""Canonical retrieval application services."""

from .dense import (
    DenseCandidate,
    DenseCandidateBatch,
    DenseCandidateCompatibilityError,
    DenseCandidateMode,
    DenseCandidateOutcome,
    DenseCandidateService,
    QueryEmbeddingProvider,
)
from .fusion import (
    FusedCandidate,
    FusionChannelRanking,
    RankedChannelCandidate,
    RetrievalChannel,
    RrfContribution,
    RrfFusionBatch,
    RrfFusionPolicy,
    reciprocal_rank_fusion,
)
from .filters import RetrievalFilterCapability, retrieval_filter_capability
from .lexical import (
    LexicalCandidateBatch,
    LexicalCandidateDecision,
    LexicalCandidateDisposition,
    LexicalCandidateOutcome,
    LexicalCandidateService,
)
from .locators import (
    CitationCandidate,
    CitationChannel,
    CitationChannelProvenance,
    CitationLocatorCatalog,
    CitationLocatorRecord,
    CitationLocatorService,
    CitationReadyHit,
    CitationResolutionBatch,
    CitationResolutionError,
    CitationResolutionErrorCode,
    CitationRetrievalMode,
    CitationSourceMetadata,
    ExactSourceLocator,
    LocatorValue,
    citation_candidates_from_dense,
    citation_candidates_from_fusion,
    citation_candidates_from_lexical,
    citation_candidates_from_rerank,
)
from .selection import (
    DeduplicationKey,
    EvidenceDeduplicationPolicy,
    EvidenceDiversityPolicy,
    EvidenceLineage,
    EvidenceSelectionBatch,
    EvidenceSelectionDecision,
    EvidenceSelectionDisposition,
    EvidenceSelectionPolicy,
    select_evidence,
)
from .reranking import (
    RerankBatch,
    RerankFailurePolicy,
    RerankOutcome,
    RerankPolicy,
    RerankResponse,
    RerankScore,
    RerankedCandidate,
    Reranker,
    rerank_candidates,
)

__all__ = [
    "CitationCandidate",
    "CitationChannel",
    "CitationChannelProvenance",
    "CitationLocatorCatalog",
    "CitationLocatorRecord",
    "CitationLocatorService",
    "CitationReadyHit",
    "CitationResolutionBatch",
    "CitationResolutionError",
    "CitationResolutionErrorCode",
    "CitationRetrievalMode",
    "CitationSourceMetadata",
    "DeduplicationKey",
    "DenseCandidate",
    "DenseCandidateBatch",
    "DenseCandidateCompatibilityError",
    "DenseCandidateMode",
    "DenseCandidateOutcome",
    "DenseCandidateService",
    "EvidenceDeduplicationPolicy",
    "EvidenceDiversityPolicy",
    "EvidenceLineage",
    "EvidenceSelectionBatch",
    "EvidenceSelectionDecision",
    "EvidenceSelectionDisposition",
    "EvidenceSelectionPolicy",
    "FusedCandidate",
    "FusionChannelRanking",
    "ExactSourceLocator",
    "LexicalCandidateBatch",
    "LexicalCandidateDecision",
    "LexicalCandidateDisposition",
    "LexicalCandidateOutcome",
    "LexicalCandidateService",
    "LocatorValue",
    "QueryEmbeddingProvider",
    "RankedChannelCandidate",
    "RetrievalChannel",
    "RetrievalFilterCapability",
    "RerankBatch",
    "RerankFailurePolicy",
    "RerankOutcome",
    "RerankPolicy",
    "RerankResponse",
    "RerankScore",
    "RerankedCandidate",
    "Reranker",
    "RrfContribution",
    "RrfFusionBatch",
    "RrfFusionPolicy",
    "citation_candidates_from_dense",
    "citation_candidates_from_fusion",
    "citation_candidates_from_lexical",
    "citation_candidates_from_rerank",
    "reciprocal_rank_fusion",
    "retrieval_filter_capability",
    "rerank_candidates",
    "select_evidence",
]
