version = 1

# Config/docs/assets: MIT
[[annotations]]
path = [
  "**/*.png", "**/*.svg", "**/*.ico", "**/*.gif", "**/*.jpg", "**/*.jpeg",
  "**/*.html", "**/*.toml", "**/*.ini", "**/*.cfg", "**/*.conf", "**/*.txt",
  "**/*.env", "**/*.env.*", "**/*.yaml", "**/*.yml", "**/*.json", "**/*.pdb",
  "**/*.cff", "**/*.dic", ".coverage*", ".gitattributes", ".gitignore",
  "models/**", "**/.editorconfig", "artifacts/**", ".idea/**", "**/*.pyc",
  "**/*.fasta", "**/*.gitkeep", "site/**", ".venv/**", "**/*.jsonl", "**/*.dvc",
  "**/*.gitignore", "**/*.hash",
]
precedence = "override"
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "© 2025 Bijan Mousavi"

# Code: MIT
[[annotations]]
path = ["src/**", "scripts/**", "**/*.py", "**/*.pyi", "**/*.sh", "**/*.mk", "Makefile", "Dockerfile", "Dockerfile.*"]
precedence = "closest"
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "© 2025 Bijan Mousavi"

# Markdown docs: MIT
[[annotations]]
path = ["**/*.md"]
precedence = "closest"
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "© 2025 Bijan Mousavi"
