# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi
"""Grounded generation inputs and evidence selection."""

from __future__ import annotations

from bijux_canon_reason.grounding.claim_normalization import (
    AtomicClaim,
    AtomicClaimNormalizer,
    AtomicClaimPolarity,
    ClaimConfidenceBasis,
    ClaimNormalizationError,
    ClaimNormalizationErrorCode,
    ClaimNormalizationOutcome,
    NormalizedClaimSet,
)
from bijux_canon_reason.grounding.extractive_synthesis import (
    CredentialFreeSynthesis,
    CredentialFreeSynthesisPolicy,
    CredentialFreeSynthesizer,
    ExtractiveSynthesisPoint,
    SynthesisOutcome,
    SynthesisStyle,
)
from bijux_canon_reason.grounding.provider_contracts import (
    CandidateOutcome,
    CandidatePolarity,
    ProviderAttemptKind,
    ProviderAttemptReceipt,
    ProviderAttemptStatus,
    StructuredCandidateClaim,
    StructuredProviderSynthesis,
    StructuredSynthesisCandidate,
)
from bijux_canon_reason.grounding.structured_provider import (
    JsonHttpResponse,
    JsonTransport,
    OpenAICompatibleStructuredSynthesizer,
    StructuredProviderConfiguration,
    StructuredProviderError,
    StructuredProviderErrorCode,
    StructuredProviderPolicy,
    UrllibJsonTransport,
    prompt_artifact_id,
    response_schema,
    response_schema_sha256,
)
from bijux_canon_reason.grounding.evidence_packets import (
    CitationEvidence,
    EvidencePacket,
    EvidencePacketBuilder,
    EvidencePacketError,
    EvidencePacketErrorCode,
    EvidencePacketPolicy,
    EvidenceSelectionDecision,
    EvidenceTrust,
    ImmutableEvidenceLocator,
    OmissionReason,
    PacketCompleteness,
    SelectionDisposition,
    TokenCounter,
    UnicodeLexicalTokenCounter,
)

__all__ = [
    "AtomicClaim",
    "AtomicClaimNormalizer",
    "AtomicClaimPolarity",
    "CandidateOutcome",
    "CandidatePolarity",
    "CitationEvidence",
    "ClaimConfidenceBasis",
    "ClaimNormalizationError",
    "ClaimNormalizationErrorCode",
    "ClaimNormalizationOutcome",
    "CredentialFreeSynthesis",
    "CredentialFreeSynthesisPolicy",
    "CredentialFreeSynthesizer",
    "EvidencePacket",
    "EvidencePacketBuilder",
    "EvidencePacketError",
    "EvidencePacketErrorCode",
    "EvidencePacketPolicy",
    "EvidenceSelectionDecision",
    "EvidenceTrust",
    "ExtractiveSynthesisPoint",
    "ImmutableEvidenceLocator",
    "JsonHttpResponse",
    "JsonTransport",
    "NormalizedClaimSet",
    "OpenAICompatibleStructuredSynthesizer",
    "OmissionReason",
    "PacketCompleteness",
    "ProviderAttemptKind",
    "ProviderAttemptReceipt",
    "ProviderAttemptStatus",
    "SelectionDisposition",
    "SynthesisOutcome",
    "SynthesisStyle",
    "StructuredCandidateClaim",
    "StructuredProviderConfiguration",
    "StructuredProviderError",
    "StructuredProviderErrorCode",
    "StructuredProviderPolicy",
    "StructuredProviderSynthesis",
    "StructuredSynthesisCandidate",
    "TokenCounter",
    "UnicodeLexicalTokenCounter",
    "UrllibJsonTransport",
    "prompt_artifact_id",
    "response_schema",
    "response_schema_sha256",
]
