# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi

include $(ROOT_MAKE_DIR)/package/canon-python.mk

PYTHON ?= python3.11
ENABLE_MYPY ?= 0
ENABLE_CODESPELL ?= 1
ENABLE_RADON ?= 1
ENABLE_PYDOCSTYLE ?= 0
ENABLE_PYTYPE ?= 0
RUFF_CHECK_FIX ?= 1
SECURITY_IGNORE_IDS ?= PYSEC-2022-42969
SECURITY_AUDIT_PREPARE_MODE ?= pyproject
PIP_AUDIT_INPUTS ?= -r "$(SECURITY_REQS)"
DOCS_DEV_ADDR ?= 0.0.0.0:8000
DOCS_EXTRA_CLEAN_PATHS ?= site docs/site
API_MODE ?= freeze
PUBLISH_DIST_DIR ?= $(PROJECT_ARTIFACTS_DIR)/release
PUBLISH_UPLOAD_ENABLED ?= 0
TEST_MAIN_ARGS ?= --maxfail=1
BUILD_DIR ?= $(PROJECT_ARTIFACTS_DIR)/release
PACKAGE_BOOTSTRAP_PREREQS ?= $(VENV)
PACKAGE_BOOTSTRAP_TARGETS ?= lint quality security api docs
PACKAGE_CLEAN_EXTRA_PATHS ?= $(COMMON_API_TEMP_CLEAN_PATHS) session.sqlite docs/site $(COMMON_CONFIG_CACHE_CLEAN_PATHS)
