# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi

"""Root package API metadata for ``bijux_canon_ingest``."""

from __future__ import annotations

from bijux_canon_ingest._lazy_exports import LazyExport

LAZY_EXPORTS: dict[str, LazyExport] = {
    "AdmissionBudgets": (".domain.source_admission", "AdmissionBudgets"),
    "AdmissionDisposition": (".domain.source_admission", "AdmissionDisposition"),
    "AdmissionEvidence": (".domain.source_admission", "AdmissionEvidence"),
    "AdmissionIssue": (".domain.source_admission", "AdmissionIssue"),
    "AdmissionIssueCode": (".domain.source_admission", "AdmissionIssueCode"),
    "AdmissionResult": (".domain.source_admission", "AdmissionResult"),
    "AppConfig": (".config.app", "AppConfig"),
    "DocsReader": (".config.ingest", "DocsReader"),
    "DiscoveredSource": (".domain.source_discovery", "DiscoveredSource"),
    "DiscoveryIssue": (".domain.source_discovery", "DiscoveryIssue"),
    "DiscoveryIssueCode": (".domain.source_discovery", "DiscoveryIssueCode"),
    "DiscoveryPolicy": (".domain.source_discovery", "DiscoveryPolicy"),
    "DiscoveryResult": (".domain.source_discovery", "DiscoveryResult"),
    "DiscoveryRoot": (".domain.source_discovery", "DiscoveryRoot"),
    "DocumentMetadata": (".domain.document_extraction", "DocumentMetadata"),
    "DocumentParseError": (".domain.document_extraction", "DocumentParseError"),
    "DocumentParseIssueCode": (
        ".domain.document_extraction",
        "DocumentParseIssueCode",
    ),
    "DocxBlockRole": (".domain.document_extraction", "DocxBlockRole"),
    "DocxDocumentMetadata": (
        ".domain.document_extraction",
        "DocxDocumentMetadata",
    ),
    "HtmlBlockRole": (".domain.document_extraction", "HtmlBlockRole"),
    "HtmlDocumentMetadata": (
        ".domain.document_extraction",
        "HtmlDocumentMetadata",
    ),
    "HtmlLink": (".domain.document_extraction", "HtmlLink"),
    "NewlineStyle": (".domain.document_extraction", "NewlineStyle"),
    "FSReader": (".interfaces.cli.document_io", "FSReader"),
    "IngestBoundaryDeps": (".config.ingest", "IngestBoundaryDeps"),
    "IngestConfig": (".config.ingest", "IngestConfig"),
    "IngestDeps": (".config.ingest", "IngestDeps"),
    "ParsedBlock": (".domain.document_extraction", "ParsedBlock"),
    "ParsedDocument": (".domain.document_extraction", "ParsedDocument"),
    "ParsedDocxBlock": (".domain.document_extraction", "ParsedDocxBlock"),
    "ParsedDocxDocument": (".domain.document_extraction", "ParsedDocxDocument"),
    "ParsedHtmlBlock": (".domain.document_extraction", "ParsedHtmlBlock"),
    "ParsedHtmlDocument": (".domain.document_extraction", "ParsedHtmlDocument"),
    "ParsedPdfDocument": (".domain.document_extraction", "ParsedPdfDocument"),
    "ParsedTextBlock": (".domain.document_extraction", "ParsedTextBlock"),
    "ParsedTextDocument": (".domain.document_extraction", "ParsedTextDocument"),
    "PdfDocumentMetadata": (
        ".domain.document_extraction",
        "PdfDocumentMetadata",
    ),
    "PdfPage": (".domain.document_extraction", "PdfPage"),
    "PdfPageExtraction": (".domain.document_extraction", "PdfPageExtraction"),
    "SourceLocator": (".domain.document_extraction", "SourceLocator"),
    "TextBlockRole": (".domain.document_extraction", "TextBlockRole"),
    "TextEncoding": (".domain.document_extraction", "TextEncoding"),
    "UnexpectedFailure": (".interfaces.errors.exception_bridge", "UnexpectedFailure"),
    "SourceFormat": (".domain.source_admission", "SourceFormat"),
    "admit_source": (".application.source_admission", "admit_source"),
    "admit_sources": (".application.source_admission", "admit_sources"),
    "build_ingest_deps": (".config.ingest", "build_ingest_deps"),
    "discover_sources": (".application.source_discovery", "discover_sources"),
    "iter_chunks_from_cleaned": (".application.pipeline", "iter_chunks_from_cleaned"),
    "iter_ingest_pipeline": (".application.pipeline", "iter_ingest_pipeline"),
    "iter_ingest_pipeline_core": (".application.pipeline", "iter_ingest_pipeline_core"),
    "make_chunk_stream_fn": (".config.ingest", "make_chunk_stream_fn"),
    "make_ingest_fn": (".config.ingest", "make_ingest_fn"),
    "parse_ingest_config": (".config.ingest_parsing", "parse_ingest_config"),
    "parse_docx": (".application.document_extraction", "parse_docx"),
    "parse_html": (".application.document_extraction", "parse_html"),
    "parse_jats": (".application.document_extraction", "parse_jats"),
    "parse_markdown": (".application.document_extraction", "parse_markdown"),
    "parse_pdf": (".application.document_extraction", "parse_pdf"),
    "parse_text": (".application.document_extraction", "parse_text"),
    "gen_bounded_chunks": (".processing.streaming", "gen_bounded_chunks"),
    "gen_grouped_chunks": (".processing.streaming", "gen_grouped_chunks"),
    "gen_stream_deduped": (".processing.streaming", "gen_stream_deduped"),
    "gen_stream_embedded": (".processing.streaming", "gen_stream_embedded"),
    "safe_rag_pipeline": (".processing.streaming", "safe_rag_pipeline"),
    "SymlinkPolicy": (".domain.source_discovery", "SymlinkPolicy"),
    "stream_chunks": (".processing.streaming", "stream_chunks"),
    "result_map_try": (".interfaces.errors.exception_bridge", "result_map_try"),
    "run_ingest_pipeline": (".application.pipeline", "run_ingest_pipeline"),
    "run_ingest_pipeline_docs": (".application.pipeline", "run_ingest_pipeline_docs"),
    "run_ingest_pipeline_path": (".application.pipeline", "run_ingest_pipeline_path"),
    "try_result": (".interfaces.errors.exception_bridge", "try_result"),
    "unexpected_fail": (".interfaces.errors.exception_bridge", "unexpected_fail"),
    "v_map_try": (".interfaces.errors.exception_bridge", "v_map_try"),
    "v_try": (".interfaces.errors.exception_bridge", "v_try"),
    "write_chunks_jsonl": (".interfaces.cli.document_io", "write_chunks_jsonl"),
}

PUBLIC_API = [
    "__version__",
    "assert_never",
    "RawDoc",
    "AdmissionBudgets",
    "AdmissionDisposition",
    "AdmissionEvidence",
    "AdmissionIssue",
    "AdmissionIssueCode",
    "AdmissionResult",
    "DocumentMetadata",
    "DocumentParseError",
    "DocumentParseIssueCode",
    "DocxBlockRole",
    "DocxDocumentMetadata",
    "HtmlBlockRole",
    "HtmlDocumentMetadata",
    "HtmlLink",
    "NewlineStyle",
    "ParsedBlock",
    "ParsedDocument",
    "ParsedDocxBlock",
    "ParsedDocxDocument",
    "ParsedHtmlBlock",
    "ParsedHtmlDocument",
    "ParsedPdfDocument",
    "ParsedTextBlock",
    "ParsedTextDocument",
    "PdfDocumentMetadata",
    "PdfPage",
    "PdfPageExtraction",
    "SourceLocator",
    "TextBlockRole",
    "TextEncoding",
    "SourceFormat",
    "admit_source",
    "admit_sources",
    "parse_docx",
    "parse_html",
    "parse_jats",
    "parse_markdown",
    "parse_pdf",
    "parse_text",
    "DiscoveredSource",
    "DiscoveryIssue",
    "DiscoveryIssueCode",
    "DiscoveryPolicy",
    "DiscoveryResult",
    "DiscoveryRoot",
    "SymlinkPolicy",
    "discover_sources",
    "CleanDoc",
    "ChunkWithoutEmbedding",
    "Chunk",
    "RagEnv",
    "TextNode",
    "TreeDoc",
    "clean_doc",
    "chunk_doc",
    "iter_chunk_spans",
    "iter_chunk_doc",
    "iter_overlapping_chunks_text",
    "embed_chunk",
    "structural_dedup_chunks",
    "DedupIterator",
    "structural_dedup_lazy",
    "identity",
    "compose",
    "flow",
    "producer_pipeline",
    "pipe",
    "fmap",
    "ffilter",
    "flatmap",
    "tee",
    "probe",
    "StageInstrumentation",
    "instrument_stage",
    "FakeTime",
    "Ok",
    "Err",
    "Result",
    "ErrInfo",
    "make_errinfo",
    "is_ok",
    "is_err",
    "map_result",
    "map_err",
    "bind_result",
    "recover",
    "unwrap_or",
    "to_option",
    "Option",
    "Some",
    "NoneVal",
    "NONE",
    "is_some",
    "is_none",
    "map_option",
    "bind_option",
    "unwrap_or_else",
    "option_from_nullable",
    "option_to_nullable",
    "map_result_iter",
    "filter_ok",
    "filter_err",
    "partition_results",
    "result_map",
    "result_and_then",
    "assert_acyclic",
    "flatten",
    "recursive_flatten",
    "iter_flatten",
    "iter_flatten_buffered",
    "flatten_via_fold",
    "max_depth",
    "fold_tree",
    "fold_tree_no_path",
    "fold_tree_buffered",
    "scan_tree",
    "linear_reduce",
    "linear_accumulate",
    "fold_count_length_maxdepth",
    "scan_count_length_maxdepth",
    "lru_cache_custom",
    "memoize_keyed",
    "DiskCache",
    "content_hash_key",
    "try_map_iter",
    "par_try_map_iter",
    "tap_ok",
    "tap_err",
    "recover_iter",
    "recover_result_iter",
    "split_results_to_sinks",
    "split_results_to_sinks_guarded",
    "ResultsBoth",
    "fold_results_fail_fast",
    "fold_results_collect_errs",
    "fold_results_collect_errs_capped",
    "fold_until_error_rate",
    "all_ok_fail_fast",
    "collect_both",
    "BreakInfo",
    "short_circuit_on_err_emit",
    "short_circuit_on_err_truncate",
    "circuit_breaker_rate_emit",
    "circuit_breaker_rate_truncate",
    "circuit_breaker_count_emit",
    "circuit_breaker_count_truncate",
    "circuit_breaker_pred_emit",
    "circuit_breaker_pred_truncate",
    "with_resource_stream",
    "managed_stream",
    "nested_managed",
    "auto_close",
    "RetryCtx",
    "RetryDecision",
    "retry_map_iter",
    "fixed_policy",
    "exp_policy",
    "is_retriable_errinfo",
    "restore_input_order",
    "ErrGroup",
    "ErrReport",
    "fold_error_counts",
    "fold_error_report",
    "report_to_jsonable",
    "DocRule",
    "Pred",
    "Eq",
    "LenGt",
    "StartsWith",
    "All",
    "AnyOf",
    "Not",
    "RulesConfig",
    "DEFAULT_RULES",
    "eval_pred",
    "any_doc",
    "none_doc",
    "category_startswith",
    "title_contains",
    "abstract_min_len",
    "rule_and",
    "rule_or",
    "rule_not",
    "rule_all",
    "parse_rule",
    "SafeVisitor",
    "assert_rule_is_safe_expr",
    "CleanConfig",
    "DEFAULT_CLEAN_CONFIG",
    "make_cleaner",
    "IngestTaps",
    "DebugConfig",
    "Observations",
    "TraceLens",
    "IngestTrace",
    "IngestConfig",
    "IngestDeps",
    "DocsReader",
    "IngestBoundaryDeps",
    "build_ingest_deps",
    "make_ingest_fn",
    "make_chunk_stream_fn",
    "parse_ingest_config",
    "_trace_iter",
    "gen_chunk_doc",
    "gen_chunk_spans",
    "gen_overlapping_chunks",
    "iter_ingest_pipeline",
    "iter_ingest_pipeline_core",
    "stream_chunks",
    "gen_stream_embedded",
    "gen_stream_deduped",
    "sliding_windows",
    "gen_grouped_chunks",
    "gen_bounded_chunks",
    "safe_rag_pipeline",
    "multicast",
    "throttle",
    "iter_chunks_from_cleaned",
    "run_ingest_pipeline",
    "run_ingest_pipeline_docs",
    "run_ingest_pipeline_path",
    "FSReader",
    "write_chunks_jsonl",
    "AppConfig",
    "Reader",
    "State",
    "Writer",
    "ask",
    "asks",
    "local",
    "get",
    "put",
    "modify",
    "run_state",
    "tell",
    "tell_many",
    "listen",
    "censor",
    "run_writer",
    "wr_pure",
    "wr_map",
    "wr_and_then",
    "transpose_result_option",
    "transpose_option_result",
    "toggle_validation",
    "toggle_logging",
    "toggle_metrics",
    "try_result",
    "result_map_try",
    "v_try",
    "v_map_try",
    "UnexpectedFailure",
    "unexpected_fail",
    "Source",
    "Transform",
    "trace_iter",
    "fence_k",
    "compose2_transforms",
    "compose_transforms",
    "source_to_transform",
    "tap_prefix",
    "make_chain",
    "make_roundrobin",
    "make_merge",
    "fork2_lockstep",
    "make_throttle",
    "make_rate_limit",
    "make_timestamp",
    "make_call_gate",
    "make_tap",
    "make_counter",
    "make_sampler_bernoulli",
    "make_sampler_periodic",
    "make_sampler_stable",
    "make_peek",
    "ensure_contiguous",
    "as_source",
]

__all__ = ["LAZY_EXPORTS", "PUBLIC_API"]
