# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi

"""Public core exports for authority, failures, and stable identifiers."""

from __future__ import annotations

from bijux_canon_runtime.core.authority import (
    SEMANTICS_SOURCE,
    SEMANTICS_VERSION,
    AuthorityToken,
    authority_token,
    enforce_runtime_semantics,
    finalize_trace,
)
from bijux_canon_runtime.core.errors import (
    ExecutionFailure,
    ReasoningFailure,
    ResolutionFailure,
    RetrievalFailure,
    SemanticViolationError,
    VerificationFailure,
)
from bijux_canon_runtime.core.ids import (
    ActionID,
    AgentID,
    ArtifactID,
    BundleID,
    ClaimID,
    ContentHash,
    ContractID,
    DatasetID,
    EnvironmentFingerprint,
    EvidenceID,
    FlowID,
    GateID,
    InputsFingerprint,
    PlanHash,
    PolicyFingerprint,
    RequestID,
    ResolverID,
    RuleID,
    RunID,
    StepID,
    TenantID,
    ToolID,
    VersionID,
)

__all__ = [
    "ActionID",
    "AgentID",
    "ArtifactID",
    "AuthorityToken",
    "BundleID",
    "ClaimID",
    "ContentHash",
    "ContractID",
    "DatasetID",
    "EnvironmentFingerprint",
    "EvidenceID",
    "ExecutionFailure",
    "FlowID",
    "GateID",
    "InputsFingerprint",
    "PlanHash",
    "PolicyFingerprint",
    "ReasoningFailure",
    "RequestID",
    "ResolverID",
    "ResolutionFailure",
    "RuleID",
    "RunID",
    "RetrievalFailure",
    "SEMANTICS_SOURCE",
    "SEMANTICS_VERSION",
    "SemanticViolationError",
    "StepID",
    "TenantID",
    "ToolID",
    "VerificationFailure",
    "VersionID",
    "authority_token",
    "enforce_runtime_semantics",
    "finalize_trace",
]
