# SPDX-License-Identifier: Apache-2.0
# Copyright © 2026 Bijan Mousavi
"""Package exports for bijux canon reason."""

from __future__ import annotations

from bijux_canon_reason._version import __version__
from bijux_canon_reason.core import (
    Claim,
    ClaimStatus,
    ClaimType,
    EvidenceRef,
    Plan,
    PlanNode,
    ProblemSpec,
    RuntimeDescriptor,
    StepOutput,
    StepSpec,
    SupportKind,
    SupportRef,
    ToolCall,
    ToolDescriptor,
    ToolRequest,
    ToolResult,
    Trace,
    TraceEvent,
    TraceEventKind,
    VerificationCheck,
    VerificationReport,
    canonical_dumps,
    fingerprint_bytes,
    fingerprint_obj,
    stable_id,
    validate_plan,
    validate_trace,
    validate_verification_report,
)
from bijux_canon_reason.grounding import (
    CitationEvidence,
    CredentialFreeSynthesis,
    CredentialFreeSynthesisPolicy,
    CredentialFreeSynthesizer,
    EvidencePacket,
    EvidencePacketBuilder,
    EvidencePacketError,
    EvidencePacketErrorCode,
    EvidencePacketPolicy,
    EvidenceSelectionDecision,
    EvidenceTrust,
    ExtractiveSynthesisPoint,
    ImmutableEvidenceLocator,
    OmissionReason,
    PacketCompleteness,
    SelectionDisposition,
    SynthesisOutcome,
    SynthesisStyle,
    TokenCounter,
    UnicodeLexicalTokenCounter,
)

__all__ = [
    "__version__",
    "Claim",
    "ClaimStatus",
    "ClaimType",
    "CitationEvidence",
    "CredentialFreeSynthesis",
    "CredentialFreeSynthesisPolicy",
    "CredentialFreeSynthesizer",
    "EvidencePacket",
    "EvidencePacketBuilder",
    "EvidencePacketError",
    "EvidencePacketErrorCode",
    "EvidencePacketPolicy",
    "EvidenceRef",
    "EvidenceSelectionDecision",
    "EvidenceTrust",
    "ExtractiveSynthesisPoint",
    "ImmutableEvidenceLocator",
    "OmissionReason",
    "Plan",
    "PlanNode",
    "ProblemSpec",
    "PacketCompleteness",
    "RuntimeDescriptor",
    "StepOutput",
    "StepSpec",
    "SupportKind",
    "SupportRef",
    "SelectionDisposition",
    "SynthesisOutcome",
    "SynthesisStyle",
    "TokenCounter",
    "ToolCall",
    "ToolDescriptor",
    "ToolRequest",
    "ToolResult",
    "Trace",
    "TraceEvent",
    "TraceEventKind",
    "UnicodeLexicalTokenCounter",
    "VerificationCheck",
    "VerificationReport",
    "canonical_dumps",
    "fingerprint_bytes",
    "fingerprint_obj",
    "stable_id",
    "validate_plan",
    "validate_trace",
    "validate_verification_report",
]
